# Render script generated by render_blend.py - 2026-02-26T00:36:08.859336
import bpy
import math
import os
import mathutils

# Open existing blend file
bpy.ops.wm.open_mainfile(filepath=r"outputs/coffee_table_20260226_003552/model.blend")

def setup_camera(name, location, rotation, ortho=True, ortho_scale=5):
    cam_data = bpy.data.cameras.new(name=name)
    cam_data.type = 'ORTHO' if ortho else 'PERSP'
    if ortho:
        cam_data.ortho_scale = ortho_scale
    cam_obj = bpy.data.objects.new(name, cam_data)
    bpy.context.scene.collection.objects.link(cam_obj)
    cam_obj.location = location
    cam_obj.rotation_euler = rotation
    return cam_obj

def setup_lighting():
    # Only add lights if scene has none
    existing_lights = [obj for obj in bpy.context.scene.objects if obj.type == 'LIGHT']
    if existing_lights:
        return  # Scene already has lighting

    key_data = bpy.data.lights.new(name="KeyLight", type='SUN')
    key_data.energy = 3.0
    key_obj = bpy.data.objects.new("KeyLight", key_data)
    bpy.context.scene.collection.objects.link(key_obj)
    key_obj.rotation_euler = (math.radians(45), math.radians(30), 0)

    fill_data = bpy.data.lights.new(name="FillLight", type='SUN')
    fill_data.energy = 1.5
    fill_obj = bpy.data.objects.new("FillLight", fill_data)
    bpy.context.scene.collection.objects.link(fill_obj)
    fill_obj.rotation_euler = (math.radians(45), math.radians(-60), 0)

    rim_data = bpy.data.lights.new(name="RimLight", type='SUN')
    rim_data.energy = 2.0
    rim_obj = bpy.data.objects.new("RimLight", rim_data)
    bpy.context.scene.collection.objects.link(rim_obj)
    rim_obj.rotation_euler = (math.radians(-30), math.radians(180), 0)

def render_view(camera, filepath, resolution):
    scene = bpy.context.scene
    scene.camera = camera
    scene.render.resolution_x = resolution[0]
    scene.render.resolution_y = resolution[1]
    scene.render.filepath = filepath
    scene.render.image_settings.file_format = 'PNG'
    bpy.ops.render.render(write_still=True)

def render_turntable(camera, output_dir, frames=12, resolution=(512, 512)):
    scene = bpy.context.scene
    scene.camera = camera
    scene.render.resolution_x = resolution[0]
    scene.render.resolution_y = resolution[1]
    scene.render.image_settings.file_format = 'PNG'

    bpy.ops.object.empty_add(location=(0, 0, 0))
    pivot = bpy.context.active_object
    pivot.name = "TurntablePivot"
    camera.parent = pivot

    for i in range(frames):
        angle = (2 * math.pi * i) / frames
        pivot.rotation_euler = (0, 0, angle)
        bpy.context.view_layer.update()
        filepath = os.path.join(output_dir, f"turntable_{i:03d}.png")
        scene.render.filepath = filepath
        bpy.ops.render.render(write_still=True)

def run():
    output_dir = r"outputs/coffee_table_20260226_003552/iteration_01/renders"
    os.makedirs(output_dir, exist_ok=True)

    # Render settings
    bpy.context.scene.render.engine = 'CYCLES'
    bpy.context.scene.cycles.samples = 64
    bpy.context.scene.cycles.use_denoising = True
    try:
        bpy.context.scene.cycles.device = 'GPU'
    except:
        bpy.context.scene.render.engine = 'BLENDER_EEVEE_NEXT'

    setup_lighting()

    # Calculate scene bounds
    min_coord = [float('inf')] * 3
    max_coord = [float('-inf')] * 3
    for obj in bpy.context.scene.objects:
        if obj.type == 'MESH':
            for corner in obj.bound_box:
                world_corner = obj.matrix_world @ mathutils.Vector(corner)
                for i in range(3):
                    min_coord[i] = min(min_coord[i], world_corner[i])
                    max_coord[i] = max(max_coord[i], world_corner[i])

    if min_coord[0] == float('inf'):
        min_coord = [-1, -1, -1]
        max_coord = [1, 1, 1]

    center = [(min_coord[i] + max_coord[i]) / 2 for i in range(3)]
    size = max(max_coord[i] - min_coord[i] for i in range(3))
    dist = size * 2
    ortho_scale = size * 1.5

    cameras = {
        'front': setup_camera('CamFront', (center[0], -dist, center[2]), (math.radians(90), 0, 0), True, ortho_scale),
        'top': setup_camera('CamTop', (center[0], center[1], dist), (0, 0, 0), True, ortho_scale),
        'side': setup_camera('CamSide', (dist, center[1], center[2]), (math.radians(90), 0, math.radians(90)), True, ortho_scale),
        'iso': setup_camera('CamIso', (dist*0.7, -dist*0.7, dist*0.7), (math.radians(54.7), 0, math.radians(45)), False),
    }

    for name, cam in cameras.items():
        filepath = os.path.join(output_dir, f"view_{name}.png")
        render_view(cam, filepath, (512, 512))

    print("[RENDER COMPLETE]")

run()
