#!/usr/bin/env python3
"""
Execute a Blender Python edit script on an existing .blend file.
Does NOT render — use render_blend.py separately after execution.

Usage:
    python execute_blender_edit.py <script_path> <blend_file_path> <output_dir>

Environment Variables:
    BLENDER_PATH: Path to Blender executable (default: "blender")
"""

import sys
import json
import subprocess
import os
import argparse
from pathlib import Path
from datetime import datetime


def main():
    parser = argparse.ArgumentParser(description="Execute Blender edit script")
    parser.add_argument("script_path", type=Path, help="Path to the edit script")
    parser.add_argument("blend_file_path", type=Path, help="Path to the .blend file to edit")
    parser.add_argument("output_dir", type=Path, help="Output directory")

    args = parser.parse_args()

    if not args.script_path.exists():
        print(json.dumps({"status": "error", "message": f"Script not found: {args.script_path}"}))
        sys.exit(1)

    if not args.blend_file_path.exists():
        print(json.dumps({"status": "error", "message": f"Blend file not found: {args.blend_file_path}"}))
        sys.exit(1)

    # Create output directory
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Prepare script with header (no render code)
    try:
        user_code = args.script_path.read_text()
        full_script = prepare_edit_script(
            user_code,
            blend_file_path=args.blend_file_path,
            output_blend_path=args.output_dir / "model.blend",
        )
    except Exception as e:
        print(json.dumps({"status": "error", "message": f"Failed to prepare script: {str(e)}"}))
        sys.exit(1)

    temp_script = args.output_dir / "full_script.py"
    temp_script.write_text(full_script)

    # Execute Blender
    blender_path = os.environ.get("BLENDER_PATH", "blender")
    result = run_blender(blender_path, temp_script, args.output_dir / "blender.log")

    if not result.get("success"):
        print(json.dumps(result))
        sys.exit(1)

    output = {
        "status": "success",
        "blend_file": str(args.output_dir / "model.blend"),
        "output_dir": str(args.output_dir),
    }

    print(json.dumps(output, indent=2))
    sys.exit(0)


def prepare_edit_script(user_code, blend_file_path, output_blend_path):
    """Inject header into user edit script. No render code appended."""
    header = f'''# Generated by Blender Full Skill (Edit) - {datetime.now().isoformat()}
import bpy
import math
import os
import mathutils

# Paths (injected by executor)
BLEND_FILE_PATH = r"{blend_file_path}"
OUTPUT_BLEND_PATH = r"{output_blend_path}"

'''

    # Remove duplicate imports from user code
    lines = []
    for line in user_code.split("\n"):
        stripped = line.strip()
        if stripped.startswith("import bpy"):
            continue
        if stripped.startswith("import math"):
            continue
        if stripped.startswith("import os"):
            continue
        lines.append(line)

    clean_code = "\n".join(lines)
    return header + clean_code


def run_blender(blender_path, script_path, log_path):
    """Execute Blender with timeout protection."""
    cmd = [str(blender_path), "--background", "--python", str(script_path)]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=180,
            env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
        )
        with open(log_path, "w") as f:
            f.write("=== STDOUT ===\n")
            f.write(result.stdout)
            f.write("\n=== STDERR ===\n")
            f.write(result.stderr)

        if result.returncode != 0:
            return {
                "status": "error",
                "message": f"Blender exited with code {result.returncode}",
                "error": result.stderr[-1000:] if result.stderr else "Unknown error",
                "log_path": str(log_path),
            }
        if "Traceback" in result.stderr or "Error:" in result.stderr:
            return {
                "status": "error",
                "message": "Blender script had errors",
                "error": extract_error(result.stderr),
                "log_path": str(log_path),
            }
        return {"success": True}
    except subprocess.TimeoutExpired:
        return {"status": "error", "message": "Blender execution timed out after 180s"}
    except FileNotFoundError:
        return {"status": "error", "message": f"Blender executable not found: {blender_path}"}


def extract_error(stderr):
    lines = stderr.strip().split("\n")
    for i, line in enumerate(lines):
        if line.startswith("Traceback"):
            return "\n".join(lines[i : min(i + 15, len(lines))])
    return "\n".join(lines[-15:])


if __name__ == "__main__":
    main()
