#!/usr/bin/env python3
"""
Execute a Blender Python script to create a new .blend file.
Does NOT render — use render_blend.py separately after execution.

Usage:
    python execute_blender.py <script_path> <output_dir>

Environment Variables:
    BLENDER_PATH: Path to Blender executable (default: "blender")
    VIBE_BLENDER_NO_BLENDER: If truthy, skip live Blender preview
    CREATE_OPEN_BLEND: If set to 0/false/no/off, skip live Blender preview
"""

import sys
import json
import subprocess
import os
from pathlib import Path
from datetime import datetime


def main():
    if len(sys.argv) < 3:
        print(json.dumps({
            "status": "error",
            "message": "Usage: execute_blender.py <script_path> <output_dir>"
        }))
        sys.exit(1)

    script_path = Path(sys.argv[1])
    output_dir = Path(sys.argv[2])

    if not script_path.exists():
        print(json.dumps({
            "status": "error",
            "message": f"Script not found: {script_path}"
        }))
        sys.exit(1)

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    # Prepare script with header (no render code)
    try:
        user_code = script_path.read_text()
        full_script = prepare_script(
            user_code,
            blend_path=output_dir / "model.blend",
        )
    except Exception as e:
        print(json.dumps({
            "status": "error",
            "message": f"Failed to prepare script: {str(e)}"
        }))
        sys.exit(1)

    temp_script = output_dir / "full_script.py"
    temp_script.write_text(full_script)

    # Execute Blender
    blender_path = os.environ.get("BLENDER_PATH", "blender")
    result = run_blender(blender_path, temp_script, output_dir / "blender.log")

    if not result.get("success"):
        print(json.dumps(result))
        sys.exit(1)

    blend_path = output_dir / "model.blend"
    live_preview = open_in_existing_blender(blend_path)

    # Return paths
    output = {
        "status": "success",
        "blend_file": str(blend_path),
        "output_dir": str(output_dir),
        "live_preview": live_preview,
    }

    print(json.dumps(output, indent=2))
    sys.exit(0)


def prepare_script(user_code, blend_path):
    """Inject header into user script. No render code appended."""
    header = f'''# Generated by blender_full Skill - {datetime.now().isoformat()}
import bpy
import math
import os

# Output paths (injected by executor)
OUTPUT_BLEND_PATH = r"{blend_path}"

# Disable Blender save backups for this run. Iteration snapshots are stored separately.
try:
    bpy.context.preferences.filepaths.save_version = 0
except Exception:
    pass

'''

    # Remove duplicate imports from user code
    lines = []
    for line in user_code.split('\n'):
        stripped = line.strip()
        if stripped.startswith('import bpy'):
            continue
        if stripped.startswith('import math'):
            continue
        if stripped.startswith('import os'):
            continue
        lines.append(line)

    clean_code = '\n'.join(lines)
    return header + clean_code


def run_blender(blender_path, script_path, log_path):
    """Execute Blender with timeout protection."""
    cmd = [str(blender_path), "--background", "--python", str(script_path)]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=90,
            env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}
        )

        # Save logs
        with open(log_path, 'w') as f:
            f.write("=== STDOUT ===\n")
            f.write(result.stdout)
            f.write("\n=== STDERR ===\n")
            f.write(result.stderr)

        if result.returncode != 0:
            return {
                "status": "error",
                "message": f"Blender exited with code {result.returncode}",
                "error": result.stderr[-500:] if result.stderr else "Unknown error",
                "log_path": str(log_path)
            }

        # Check for Python errors in stderr
        if "Traceback" in result.stderr or "Error:" in result.stderr:
            return {
                "status": "error",
                "message": "Blender script had errors",
                "error": extract_error(result.stderr),
                "log_path": str(log_path)
            }

        return {"success": True}

    except subprocess.TimeoutExpired:
        return {
            "status": "error",
            "message": "Blender execution timed out after 90s",
            "fix": "Simplify the script or reduce modifier complexity"
        }
    except FileNotFoundError:
        return {
            "status": "error",
            "message": f"Blender executable not found: {blender_path}",
            "fix": "Set BLENDER_PATH environment variable or install Blender"
        }


def is_truthy(value):
    if not value:
        return False
    normalized = value.strip().lower()
    return normalized in {"1", "true", "yes", "on"}


def open_in_existing_blender(blend_path):
    """Open the generated blend in an existing Blender app without launching a new app instance."""
    if is_truthy(os.environ.get("VIBE_BLENDER_NO_BLENDER")):
        return {"attempted": False, "opened": False, "reason": "disabled-by-no-blender-mode"}

    if not is_truthy(os.environ.get("CREATE_OPEN_BLEND", "1")):
        return {"attempted": False, "opened": False, "reason": "disabled-by-create-open-blend"}

    if sys.platform != "darwin":
        return {"attempted": False, "opened": False, "reason": "unsupported-platform"}

    try:
        running = subprocess.run(["pgrep", "-x", "Blender"], capture_output=True, text=True, timeout=5)
        if running.returncode != 0:
            return {"attempted": False, "opened": False, "reason": "blender-not-running"}
    except Exception as e:
        return {"attempted": False, "opened": False, "reason": f"failed-to-check-blender-process: {e}"}

    try:
        result = subprocess.run(["open", "-a", "Blender", str(blend_path)], capture_output=True, text=True, timeout=10)
        if result.returncode != 0:
            error_text = (result.stderr or result.stdout or "").strip()
            return {
                "attempted": True,
                "opened": False,
                "reason": f"open-command-failed: {error_text or 'unknown error'}",
            }
        return {"attempted": True, "opened": True, "reason": "opened-in-existing-blender"}
    except Exception as e:
        return {"attempted": True, "opened": False, "reason": f"open-command-exception: {e}"}


def extract_error(stderr):
    """Extract relevant error from stderr."""
    lines = stderr.strip().split('\n')
    for i, line in enumerate(lines):
        if line.startswith("Traceback"):
            # Return traceback + next 10 lines
            return '\n'.join(lines[i:min(i+10, len(lines))])
    # No traceback, return last 10 lines
    return '\n'.join(lines[-10:])


if __name__ == "__main__":
    main()
