#!/usr/bin/env python3
"""
Inspect a .blend file and report its structure.

Outputs a JSON report of scene contents: objects, materials, cameras,
lights, collections, modifiers, constraints, and scene settings.

Usage:
    python inspect_blend.py <blend_path> [--detail full|summary]

Environment Variables:
    BLENDER_PATH: Path to Blender executable (default: "blender")
"""

import sys
import json
import subprocess
import os
import argparse
from pathlib import Path
from datetime import datetime


def main():
    parser = argparse.ArgumentParser(description="Inspect a .blend file structure")
    parser.add_argument("blend_path", type=Path, help="Path to the .blend file")
    parser.add_argument(
        "--detail",
        choices=["summary", "full"],
        default="full",
        help="Detail level: summary (counts only) or full (all properties)",
    )

    args = parser.parse_args()

    if not args.blend_path.exists():
        print(json.dumps({"status": "error", "message": f"Blend file not found: {args.blend_path}"}))
        sys.exit(1)

    # Build inspection script
    inspect_script = build_inspect_script(args.blend_path, args.detail)

    # Write temp script
    temp_dir = Path("/tmp/blender_inspect")
    temp_dir.mkdir(parents=True, exist_ok=True)
    temp_script = temp_dir / "inspect_script.py"
    temp_script.write_text(inspect_script)

    output_json = temp_dir / "inspect_result.json"

    blender_path = os.environ.get("BLENDER_PATH", "blender")
    result = run_blender(blender_path, temp_script, temp_dir / "blender.log")

    if not result.get("success"):
        print(json.dumps(result))
        sys.exit(1)

    # Read and output the result
    if output_json.exists():
        report = json.loads(output_json.read_text())
        print(json.dumps(report, indent=2))
    else:
        print(json.dumps({"status": "error", "message": "Inspection produced no output"}))
        sys.exit(1)


def build_inspect_script(blend_path, detail):
    """Build a Blender script that inspects the scene and outputs JSON."""
    return f'''# Inspect script generated by inspect_blend.py - {datetime.now().isoformat()}
import bpy
import json
import math
import os

bpy.ops.wm.open_mainfile(filepath=r"{blend_path}")

def vec_to_list(v):
    return [round(x, 4) for x in v]

def euler_to_degrees(e):
    return [round(math.degrees(x), 2) for x in e]

def inspect_scene(detail="{detail}"):
    scene = bpy.context.scene
    report = {{
        "status": "success",
        "blend_file": r"{blend_path}",
        "scene": {{
            "name": scene.name,
            "frame_range": [scene.frame_start, scene.frame_end],
            "fps": scene.render.fps,
            "render_engine": scene.render.engine,
            "resolution": [scene.render.resolution_x, scene.render.resolution_y],
        }},
        "counts": {{
            "objects": len(bpy.data.objects),
            "meshes": len([o for o in bpy.data.objects if o.type == 'MESH']),
            "cameras": len([o for o in bpy.data.objects if o.type == 'CAMERA']),
            "lights": len([o for o in bpy.data.objects if o.type == 'LIGHT']),
            "empties": len([o for o in bpy.data.objects if o.type == 'EMPTY']),
            "armatures": len([o for o in bpy.data.objects if o.type == 'ARMATURE']),
            "curves": len([o for o in bpy.data.objects if o.type == 'CURVE']),
            "materials": len(bpy.data.materials),
            "collections": len(bpy.data.collections),
        }},
    }}

    if detail == "summary":
        # Just list object names grouped by type
        by_type = {{}}
        for obj in bpy.data.objects:
            t = obj.type
            if t not in by_type:
                by_type[t] = []
            by_type[t].append(obj.name)
        report["objects_by_type"] = by_type
        report["material_names"] = [m.name for m in bpy.data.materials]
        report["collection_names"] = [c.name for c in bpy.data.collections]
    else:
        # Full detail
        objects = []
        for obj in bpy.data.objects:
            obj_info = {{
                "name": obj.name,
                "type": obj.type,
                "location": vec_to_list(obj.location),
                "rotation_euler_deg": euler_to_degrees(obj.rotation_euler),
                "scale": vec_to_list(obj.scale),
                "visible": obj.visible_get(),
                "parent": obj.parent.name if obj.parent else None,
            }}

            # Mesh-specific
            if obj.type == 'MESH' and obj.data:
                obj_info["mesh"] = {{
                    "vertices": len(obj.data.vertices),
                    "edges": len(obj.data.edges),
                    "faces": len(obj.data.polygons),
                }}
                # Bounding box
                bb = obj.bound_box
                obj_info["bound_box_local"] = {{
                    "min": vec_to_list(bb[0]),
                    "max": vec_to_list(bb[6]),
                }}
                # Modifiers
                if obj.modifiers:
                    obj_info["modifiers"] = [
                        {{"name": m.name, "type": m.type}}
                        for m in obj.modifiers
                    ]
                # Materials
                if obj.data.materials:
                    obj_info["materials"] = [m.name if m else None for m in obj.data.materials]
                # Shape keys
                if obj.data.shape_keys:
                    obj_info["shape_keys"] = [
                        {{"name": kb.name, "value": round(kb.value, 4)}}
                        for kb in obj.data.shape_keys.key_blocks
                    ]

            # Camera-specific
            elif obj.type == 'CAMERA' and obj.data:
                obj_info["camera"] = {{
                    "type": obj.data.type,
                    "lens": round(obj.data.lens, 2) if obj.data.type == 'PERSP' else None,
                    "ortho_scale": round(obj.data.ortho_scale, 2) if obj.data.type == 'ORTHO' else None,
                    "clip_start": round(obj.data.clip_start, 4),
                    "clip_end": round(obj.data.clip_end, 2),
                }}

            # Light-specific
            elif obj.type == 'LIGHT' and obj.data:
                obj_info["light"] = {{
                    "type": obj.data.type,
                    "energy": round(obj.data.energy, 2),
                    "color": vec_to_list(obj.data.color),
                }}

            # Constraints
            if obj.constraints:
                obj_info["constraints"] = [
                    {{"name": c.name, "type": c.type}}
                    for c in obj.constraints
                ]

            objects.append(obj_info)

        report["objects"] = objects

        # Materials detail
        materials = []
        for mat in bpy.data.materials:
            mat_info = {{"name": mat.name, "use_nodes": mat.use_nodes}}
            if mat.use_nodes and mat.node_tree:
                bsdf = mat.node_tree.nodes.get("Principled BSDF")
                if bsdf:
                    mat_info["principled_bsdf"] = {{
                        "base_color": vec_to_list(bsdf.inputs["Base Color"].default_value),
                        "metallic": round(bsdf.inputs["Metallic"].default_value, 3),
                        "roughness": round(bsdf.inputs["Roughness"].default_value, 3),
                    }}
                    # Check for transmission (glass)
                    try:
                        trans = bsdf.inputs["Transmission"].default_value
                        if trans > 0:
                            mat_info["principled_bsdf"]["transmission"] = round(trans, 3)
                            mat_info["principled_bsdf"]["ior"] = round(bsdf.inputs["IOR"].default_value, 3)
                    except:
                        pass
            materials.append(mat_info)
        report["materials"] = materials

        # Collections
        collections = []
        for col in bpy.data.collections:
            collections.append({{
                "name": col.name,
                "objects": [o.name for o in col.objects],
            }})
        report["collections"] = collections

        # World settings
        if scene.world:
            report["world"] = {{"name": scene.world.name}}

    # Write to file
    output_path = r"/tmp/blender_inspect/inspect_result.json"
    with open(output_path, "w") as f:
        json.dump(report, f, indent=2)
    print(f"[INSPECT COMPLETE] Written to {{output_path}}")

inspect_scene()
'''


def run_blender(blender_path, script_path, log_path):
    """Execute Blender with timeout protection."""
    cmd = [str(blender_path), "--background", "--python", str(script_path)]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
            env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
        )
        with open(log_path, "w") as f:
            f.write("=== STDOUT ===\n")
            f.write(result.stdout)
            f.write("\n=== STDERR ===\n")
            f.write(result.stderr)

        if result.returncode != 0:
            return {
                "status": "error",
                "message": f"Blender exited with code {result.returncode}",
                "error": result.stderr[-1000:] if result.stderr else "Unknown error",
                "log_path": str(log_path),
            }
        if "Traceback" in result.stderr or "Error:" in result.stderr:
            return {
                "status": "error",
                "message": "Blender script had errors",
                "error": extract_error(result.stderr),
                "log_path": str(log_path),
            }
        return {"success": True}
    except subprocess.TimeoutExpired:
        return {"status": "error", "message": "Blender execution timed out after 60s"}
    except FileNotFoundError:
        return {"status": "error", "message": f"Blender executable not found: {blender_path}"}


def extract_error(stderr):
    lines = stderr.strip().split("\n")
    for i, line in enumerate(lines):
        if line.startswith("Traceback"):
            return "\n".join(lines[i : min(i + 15, len(lines))])
    return "\n".join(lines[-15:])


if __name__ == "__main__":
    main()