# Generated by blender_full Skill - 2026-02-26T01:23:33.103631
import bpy
import math
import os

# Output paths (injected by executor)
OUTPUT_BLEND_PATH = r"outputs/teahouse_20260226_012309/model.blend"

# Disable Blender save backups for this run. Iteration snapshots are stored separately.
try:
    bpy.context.preferences.filepaths.save_version = 0
except Exception:
    pass


OUTPUT_BLEND_PATH = "outputs/teahouse_20260226_012309/model.blend"

# Clear scene
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

def create_material(name, color, roughness=0.8):
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    bsdf = nodes.get("Principled BSDF")
    bsdf.inputs['Base Color'].default_value = color
    bsdf.inputs['Roughness'].default_value = roughness
    return mat

# Materials
wood_mat = create_material("Wood", (0.1, 0.05, 0.02, 1.0)) # Dark aged wood
plaster_mat = create_material("Plaster", (0.85, 0.8, 0.7, 1.0)) # Earthy off-white
paper_mat = create_material("Paper", (0.9, 0.9, 0.85, 1.0), 0.5) # Translucent rice paper
tatami_mat = create_material("Tatami", (0.6, 0.6, 0.4, 1.0)) # Woven straw

# Floor (4.5 Tatami Mats)
# Each tatami is roughly 0.9m x 1.8m
# 4.5 layout: 2 horizontal, 2 vertical, 0.5 central
floor_size = 2.7 # 3 * 0.9m
bpy.ops.mesh.primitive_plane_add(size=floor_size, location=(0, 0, 0))
floor = bpy.context.active_object
floor.name = "Floor_Tatami"
floor.data.materials.append(tatami_mat)

# Frame and Walls
# Height ~ 2.2m
height = 2.2
thick = 0.1

def add_beam(name, pos, size, mat):
    bpy.ops.mesh.primitive_cube_add(size=1, location=pos)
    beam = bpy.context.active_object
    beam.name = name
    beam.scale = size
    beam.data.materials.append(mat)
    return beam

# Posts
posts_pos = [
    (-1.35, -1.35, height/2), (1.35, -1.35, height/2),
    (1.35, 1.35, height/2), (-1.35, 1.35, height/2),
    (0.45, 1.35, height/2) # Post for Tokonoma
]
for i, pos in enumerate(posts_pos):
    add_beam(f"Post_{i}", pos, (thick, thick, height), wood_mat)

# Walls (Back, Left, Right, Front)
# Back wall (with Tokonoma)
add_beam("Wall_Back_Left", (-0.9, 1.35, height/2), (0.9, 0.05, height), plaster_mat)
# Tokonoma (recessed area)
add_beam("Tokonoma_Back", (0.9, 1.45, height/2), (0.9, 0.05, height), plaster_mat)
add_beam("Tokonoma_Floor", (0.9, 1.35, 0.05), (0.9, 0.1, 0.1), wood_mat)

# Left wall
add_beam("Wall_Left", (-1.35, 0, height/2), (0.05, 2.7, height), plaster_mat)

# Right wall (with Nijiriguchi)
# Lower part
add_beam("Wall_Right_Lower", (1.35, 0, 0.3), (0.05, 2.7, 0.6), plaster_mat)
# Upper part
add_beam("Wall_Right_Upper", (1.35, 0, 1.6), (0.05, 2.7, 1.2), plaster_mat)
# Side parts for Nijiriguchi
add_beam("Wall_Right_Side1", (1.35, -1.0, 0.95), (0.05, 0.7, 0.7), plaster_mat)
add_beam("Wall_Right_Side2", (1.35, 1.0, 0.95), (0.05, 0.7, 0.7), plaster_mat)

# Nijiriguchi Door (small sliding)
add_beam("Nijiriguchi_Door", (1.38, 0, 0.45), (0.02, 0.6, 0.6), wood_mat)

# Front Wall (Shoji screens)
add_beam("Wall_Front_Frame", (0, -1.35, height/2), (2.7, 0.05, height), wood_mat)
# Paper screens
add_beam("Shoji_1", (-0.675, -1.33, height/2), (1.3, 0.01, 2.0), paper_mat)
add_beam("Shoji_2", (0.675, -1.33, height/2), (1.3, 0.01, 2.0), paper_mat)

# Roof (Simple gabled/hipped mix)
bpy.ops.mesh.primitive_cone_add(vertices=4, radius1=2.2, radius2=0, depth=1.5, location=(0, 0, height + 0.4))
roof = bpy.context.active_object
roof.name = "Roof"
roof.rotation_euler[2] = math.radians(45)
roof.scale[2] = 0.5
roof.data.materials.append(wood_mat)

# Final Save
bpy.ops.wm.save_as_mainfile(filepath=OUTPUT_BLEND_PATH)
