# Generated by blender_full Skill - 2026-02-25T23:14:23.405446
import bpy
import math
import os

# Output paths (injected by executor)
OUTPUT_BLEND_PATH = r"outputs/coffee_table_20260225/iteration_01/model.blend"

# Modern Coffee Table script

# 1. Clear scene
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

# 2. Create Table Top
bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0, 0, 0.425))
top = bpy.context.active_object
top.name = "TableTop"
top.scale = (1.2 / 2, 0.8 / 2, 0.05 / 2) # Cube size 1 means radius 0.5. So for 1.2m width, scale is 1.2/2.
# Apply scale
bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

# Add bevel to top
bevel_mod = top.modifiers.new(name="Bevel", type='BEVEL')
bevel_mod.width = 0.005
bevel_mod.segments = 5

# 3. Create Legs
leg_radius = 0.02
leg_height = 0.4
leg_offset_x = 0.55
leg_offset_y = 0.35

positions = [
    (leg_offset_x, leg_offset_y),
    (leg_offset_x, -leg_offset_y),
    (-leg_offset_x, leg_offset_y),
    (-leg_offset_x, -leg_offset_y)
]

legs = []
for i, pos in enumerate(positions):
    bpy.ops.mesh.primitive_cylinder_add(radius=leg_radius, depth=leg_height, location=(pos[0], pos[1], leg_height/2))
    leg = bpy.context.active_object
    leg.name = f"Leg_{i+1}"
    legs.append(leg)

# 4. Materials
# Wood Material
wood_mat = bpy.data.materials.new(name="WalnutWood")
wood_mat.use_nodes = True
bsdf = wood_mat.node_tree.nodes.get("Principled BSDF")
bsdf.inputs["Base Color"].default_value = (0.15, 0.08, 0.04, 1.0) # Dark brown
bsdf.inputs["Roughness"].default_value = 0.3
top.data.materials.append(wood_mat)

# Metal Material
metal_mat = bpy.data.materials.new(name="MatteBlackMetal")
metal_mat.use_nodes = True
bsdf_metal = metal_mat.node_tree.nodes.get("Principled BSDF")
bsdf_metal.inputs["Base Color"].default_value = (0.02, 0.02, 0.02, 1.0) # Near black
bsdf_metal.inputs["Metallic"].default_value = 1.0
bsdf_metal.inputs["Roughness"].default_value = 0.4
for leg in legs:
    leg.data.materials.append(metal_mat)

# 5. Save
bpy.ops.wm.save_as_mainfile(filepath=OUTPUT_BLEND_PATH)
